### ISSUE TITLE
Write after end error when piping the stream you should consume

### ISSUE THREAD

**Issue by sprijk** [juliangruber/reconnect-core#13]
When I pipe the stream I should consume, I get an `Error: write after end` after a reconnect.

The problem can be replicated using the code below:

``` coffee
inject       = require "reconnect-core"
net          = require "net"
{ Writable } = require "stream"

class WS extends Writable
  constructor: ->
    super

  _write: (chunk, encoding, cb) ->
    console.log "chunk", chunk.toString()
    cb()

ws = new WS
ws.on "to-disk", (data) ->
  console.log data.toString()

server = net.createServer  (client) ->
  client.write "Hello?"

  setTimeout ->
    # kill the client here
    client.destroy()
  , 2000

server.listen 1337

reconnect = inject ->
  net.connect.apply null, arguments

re = reconnect {}, (stream) ->
  # consume the stream
  stream.pipe ws
  # stream.on "data", (data) -> console.log "data", data.toString()

re
  .on 'connect', (con) ->
    console.log 'connect'
  .on 'reconnect', (n, delay) ->
    console.log 'reconnect', n, delay
   .on 'disconnect', (error) ->
    console.log 'disconnect', error
  .connect 1337
```

When I change `stream.pipe ws` to `stream.on "data", (data) -> console.log "data", data.toString()` (stream fallback mode) it does reconnect.

**Comment by moll** [comment]
@sprijk: Have you since found a module that abstracts over the stream administration? Reconnect-Core is useful, but could use another layer of indirection. ^_^

**Comment by sprijk** [comment]
In the end I, re-piped on "connected" using a class that uses `reconnect-client`. 
https://gist.github.com/sprijk/0cf588ea78f1f0e7db02

**Comment by marcelklehr** [comment]
For anyone having the same problem, [tmp-stream](https://www.npmjs.com/package/tmp-stream) is a very nice solution.

**Comment by marcelklehr** [comment]
I ended up using a hack to prevent the `end` from being propagated through the pipe:

```js
.on('connect', function (stream) {
      stream.pipe(plex).pipe(stream)
      // Don't pass through the `end`!
      var listeners = stream.listeners('end')
      stream.removeListener('end', listeners[listeners.length-1])
      // clean up on end
      stream.on('end', () => {
        stream.unpipe()
        plex.unpipe(stream)
      })
})
```

**Comment by oxgen1** [comment]
the end option on pipe worked for me with a similar issue: 
https://nodejs.org/dist/latest-v16.x/docs/api/stream.html#readablepipedestination-options
