### ISSUE TITLE
disconnect() call backoffMethod.backoff();

### ISSUE THREAD

**Issue by hij1nx** [juliangruber/reconnect-core#14]
It might be practical for the `emitter.disconnect()` method to call `backoff()`. A use case might be that you want to teardown a test and disconnect all clients as well as close all servers they are connected to; If the server closes before the client, the client will get stuck trying to reconnect to it. Would you be open to a patch for this?

**Comment by hij1nx** [comment]
Hmm, actually, I see the intent of `disconnect` is to *force a reconnect* where to close it you just `close()`. That makes sense, calling `close()` on this issue :)

**Comment by juliangruber** [comment]
nice pun! :D

**Comment by hij1nx** [comment]
Maybe I prematurely closed this. Would it make sense to have another method to kill the backoff (clear any in-flight timers), disconnect and close the stream?

**Comment by hij1nx** [comment]
maybe something like this, which seems to work for me at the moment...

```js
   emitter.disconnect = function (destroy) {
     if (destroy) {
       backoffMethod.reset()
       backoffMethod.removeAllListeners()
     }

     this.reconnect = false

     if(emitter._connection)
       emitter._connection.end()

     return emitter
   }
```

**Comment by hij1nx** [comment]
hmm, now im having trouble proving that this might even be a problem for me. Well, hopefully it's not and if the problem comes up in reality i'll reopen this.
