### ISSUE TITLE
Unhandled "error" event

### ISSUE THREAD

**Issue by itamarwe** [juliangruber/reconnect-core#18]
I'm trying to use the latest version of reconnect-core with tls, but keep getting an unhandled "error" event message.

When I try to use version ~0.0.1 of reconnect-core, it works. I also noticed that libraries such as reconnect-net use an earlier version of reconnect-core.

Here is my code:
````
var tls = require('tls');
var inject = require('reconnect-core');
var slice = [].slice;

module.exports = inject(function(){
    var args = slice.call(arguments);
    var tlsStream = tls.connect.apply(tls, args);
    tlsStream.on('secureConnect', function(){
        tlsStream.emit('connect');
    });
    return tlsStream;
});
````

And here is the error I get:
````
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
````

**Comment by juliangruber** [comment]
did you add en error listener to the reconnect instance? underlying errors are forwarded here https://github.com/juliangruber/reconnect-core/blob/master/index.js#L66

**Comment by itamarwe** [comment]
No. But then I'll suggest to update the example in the readme.
