### ISSUE TITLE
Force Try Reconnect

### ISSUE THREAD

**Issue by algrant** [juliangruber/reconnect-core#23]
Hi,

Maybe I'm just not understanding how to do it, but everything I've tried has resulted with multiple connections...

What I'm interested in is letting a connection back-off until it's only trying to reconnect every 30 secs or 5 mins or whatever - but have the option of forcing a reboot of that back-off at some point (i.e. not worry about the connection again until some user tries to connect to it). 

I guess I could destroy & re-init the whole reconnect module, but I feel like this use case is/should be already taking care of by the module itself.

Am I missing something?

Thanks!
Al

**Comment by juliangruber** [comment]
first, i added missing option docs: https://github.com/juliangruber/reconnect-core#usage. so that should have your `.initialDelay` option

**Comment by juliangruber** [comment]
for resetting, we need to expose `.reset` from the backoff module, I'll try to come up with a patch

**Comment by algrant** [comment]
Here's all I added in for my own purposes - I could make a formal pull request but I haven't done real testing particularly!

      emitter.resetBackOff = function () {
        backoffMethod.reset();
        attempt(0, 0);
      }

**Comment by juliangruber** [comment]
@algrant there's https://github.com/juliangruber/reconnect-core/pull/24, i added the missing `attempt` call by your suggestion. if you +1 i'll merge and release

**Comment by algrant** [comment]
Sorry! This slipped my mind, but yeah, that's what I've been using!

+1

**Comment by juliangruber** [comment]
published as 1.1.0
