### ISSUE TITLE
what is reconnect module?

### ISSUE THREAD

**Issue by breaklee** [juliangruber/reconnect-core#28]
sorry for question to issue.
i'm using some node module(xmpp-core, xmpp-server, etc).
and these modules are use reconnect-core.

so, i setted up reconnect option true in server options.
and below is code

```javascript
client.on("reconnect", function(dt1, dt2) {
    system.debug("reconnect", client.uid, client.name, dt1, dt2);
});
```

- question
  reconnect event has fired after socket close. ( below is sample console )
  value 0 retrycount, value 1000 delay
```xml
close f5bdb812-70d4-11e5-87cf-08002784a403,test-01
reconnect f5bdb812-70d4-11e5-87cf-08002784a403,test-01, 0, 1000
```
- question
- sometimes client.uid, client.name is null. maybe i think, socket instance has changed.
```xml
reconnect null, null, 0, 1000
```
- question
when 'reconnect' event has fired exactly?

**Comment by juliangruber** [comment]
Hey, please open this issue on a xmpp repo
