### ISSUE TITLE
Allow custom backoff strategy

### ISSUE THREAD

**Issue by wayne-nlt** [juliangruber/reconnect-core#32]
Hi There,
It would be really handy for our product if we could set a custom backoff strategy.
I'm thinking this should be pretty straight forward to implement, we could look at the type of the type option passed in, if it is a string, use one of the backoff built in strategies. If it is a function, assume it is a backoff strategy, and create a new backoff instance that utilises that.

I'm happy to help out with the code if you think this is a valid idea.
Thanks,
Wayne

**Comment by juliangruber** [comment]
I totally think it's a valid idea. Would it work for you to be able to pass in an object that has the same api as backoff?

**Comment by wayne-nlt** [comment]
Yeah, I said function above, but I meant an object that implements a backoff strategy: https://github.com/MathieuTurcotte/node-backoff#interface-backoffstrategy

**Comment by wayne-nlt** [comment]
Ahh, or were you thinking a complete replacement, so you could throw in your own backoff instance? 
e.g.
`var re = reconnect({
  // all options are optional
  initialDelay: 1e3,
  maxDelay: 30e3,
  type: new Backoff(myStrategy),
  failAfter: Infinity,
  randomisationFactor: 0,
  immediate: false
}, function (stream) {
  // stream = the stream you should consume 
})`

Either way is fine with me

**Comment by juliangruber** [comment]
both work for me :) if you want just create a pull request with the simplest solution

**Comment by wayne-nlt** [comment]
Thanks, fixed in #33
