### ISSUE TITLE
[docs] Why exposing the emitter to createConnection?

### ISSUE THREAD

**Issue by gautaz** [juliangruber/reconnect-core#36]
Hello,

Looking at [index.js#L44](../blob/master//index.js#L44), I was wondering why the `emitter` is passed as `this` to the `createConnection` method while calling it.

I have looked at both [reconnect-net](https://github.com/juliangruber/reconnect-net/blob/master/index.js) and [reconnect-engine](https://github.com/juliangruber/reconnect-engine/blob/master/index.js) and I do not see when the `this` as an event emitter is used in both contexts.

It seems that exposing this inner `emitter` is intentional as it is tested [here](../blob/master/test/connection.js#L51) but the test does not tell much about its usage.

Can you please detail which use cases it pertains to?

**Comment by juliangruber** [comment]
you're right that it's not documented anywhere, and maybe even no one uses it. But for the case that someone uses it, i'd leave it in here.

Do you think that will work?

**Comment by gautaz** [comment]
> Do you think that will work?

Yes ! I'm ok with this, in the meantime I have found a package that uses it, see:

https://github.com/rapid7/le_node/blob/master/src/logger.js#L168

The feature is in fact needed when one wants `reconnect-core` to emit events like `error` or `connect` during the initialization of the connection. It might also be needed if one wants `reconnect-core` to (re)emit custom events.

Not sure about all this but once it's clearer, I guess that some documentation on this particular subject might help.

Perhaps @piranna has more insight on this feature as he is the author of [the modification that introduced it](https://github.com/juliangruber/reconnect-core/commit/33246ae1dc8794e784a61c24e40cd03840a42474).

Do you want me to close the issue or do you rather want to keep it until there is enough material to start a PR to improve the documentation?

**Comment by juliangruber** [comment]
Ok, thanks for investigating! I think we should keep this open and add docs, I'll just rename the issue :)

**Comment by piranna** [comment]
> The feature is in fact needed when one wants reconnect-core to emit events like error or connect during the initialization of the connection. It might also be needed if one wants reconnect-core to (re)emit custom events.

Yes, that's for it. On regular network objects, the `connect` event is emitted having the event handler called with the emitting object itself as `this`, so this mimics it and makes behaviour consistent. People usually don't call events defining a `this` object so it could seems strange, but the fact it's that's a bad habit and plainly incorrect, and more specially in this context where not doing so deviates the behaviour when using `reconnect-core` from the expected one with native APIs (it's said, it's a bug).

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
